"""Add is_public to exam and exercise

Revision ID: b05e912c399b
Revises: 0008_add_missing_columns
Create Date: 2026-07-28 12:26:37.515124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b05e912c399b'
down_revision: Union[str, None] = '0008_add_missing_columns'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_exam_exercises_exam_id'), table_name='exam_exercises')
    op.drop_index(op.f('ix_exam_exercises_exercise_id'), table_name='exam_exercises')
    op.add_column('exams', sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('exams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_exams_active'), table_name='exams', postgresql_where='(deleted_at IS NULL)')
    op.add_column('exercises', sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('invite_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scan_submissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_scan_submissions_active'), table_name='scan_submissions', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('ix_scan_submissions_pseudonym'), table_name='scan_submissions')
    op.create_index(op.f('ix_scan_submissions_pseudonym_hmac'), 'scan_submissions', ['pseudonym_hmac'], unique=False)
    op.drop_index(op.f('uq_student_identities_hmac_exam'), table_name='student_identities')
    op.alter_column('teachers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('teachers_email_key'), 'teachers', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('teachers_email_key'), 'teachers', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('teachers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('uq_student_identities_hmac_exam'), 'student_identities', ['pseudonym_hmac', 'exam_id'], unique=True)
    op.drop_index(op.f('ix_scan_submissions_pseudonym_hmac'), table_name='scan_submissions')
    op.create_index(op.f('ix_scan_submissions_pseudonym'), 'scan_submissions', ['pseudonym_hmac'], unique=False)
    op.create_index(op.f('ix_scan_submissions_active'), 'scan_submissions', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.alter_column('scan_submissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('invite_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('exercises', 'is_public')
    op.create_index(op.f('ix_exams_active'), 'exams', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.alter_column('exams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('exams', 'is_public')
    op.create_index(op.f('ix_exam_exercises_exercise_id'), 'exam_exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exam_exercises_exam_id'), 'exam_exercises', ['exam_id'], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
